# runtime: python39
# entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT
# instance_class: F2

# env_variables:
#   MODEL_URL: 'YOUR_MODEL_URL'
#   SECRET_KEY: 'YOUR_SECRET_KEY'
#   ALGORITHM: 'YOUR_ALGORITHM'

# handlers:
# - url: /.*
#   script: auto

# runtime_config:
#   python_version: 3

runtime: custom
env: flex

service: default

instance_class: F2

env_variables:
  MODEL_URL: 'https://storage.googleapis.com/capstonegacor-bucket/model-in-prod/model.h5'
  SECRET_KEY: 'Iy2OWmXmMgxvL3cfmb8tGcQfvZSQ2Hm6Yz-WCWTG69A'
  ALGORITHM: 'HS256'

manual_scaling:
  instances: 1
