runtime: python39
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT
instance_class: F2

env_variables:
  MODEL_URL: 'YOUR_MODEL_URL'
  SECRET_KEY: 'YOUR_SECRET_KEY'
  ALGORITHM: 'YOUR_ALGORITHM'

handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3