const predictionData = [
  {
    name: "Atopic Dermatitis",
    link: "https://www.alodokter.com/eksim-atopik#:~:text=Pengobatan%20dermatitis%20atopik%20bertujuan%20untuk,serta%20perawatan%20mandiri%20di%20rumah",
    step: "Pengobatan dermatitis atopik bertujuan untuk meredakan gejala yang muncul, seperti kulit kemerahan, rasa gatal, hingga infeksi. Metode pengobatannya meliputi pemberian obat eksim, krim pelembap, terapi khusus, serta perawatan mandiri di rumah.\n1. Kenali dan hindari zat, makanan, dan minuman yang memicu gejala.\n2. Pastikan bayi selalu berada di ruangan bersuhu sejuk dan nyaman\n3. Ganti pakaian bayi dengan rutin jika bayi berkeringat\n4. Ganti popok bayi secara berkala.\n5. Jangan menggunakan air yang terlalu panas ketika memandikan bayi.\n6. Gunakan sampo dan sabun khusus untuk bayi.\n7. Hindari memandikan bayi terlalu lama.\n8. Oleskan obat oles dermatitis atopik yang diresepkan dokter dalam keadaan kulit bayi masih lembap setelah dimandikan.",
  },
  {
    name: "Benign keratosis",
    link: "https://www.alodokter.com/keratosis-seboroik",
    step: "Keratosis seboroik umumnya tidak memerlukan pengobatan khusus. Namun, jika benjolan mengalami iritasi atau infeksi, dokter perlu mengangkatnya. Benjolan juga bisa diangkat jika pasien merasa keratosis seboroik menimbulkan ketidaknyamanan dan mengganggu penampilan.\nBeberapa metode pengangkatan benjolan keratosis seboroik yang dapat dijalani pasien adalah:\n1. Krioterapi\nPada krioterapi, dokter akan membekukan benjolan keratosis seboroik dengan menggunakan nitrogen cair untuk menghilangkan benjolan. Namun, prosedur ini biasanya tidak disarankan jika benjolan sangat tebal.\n2. Terapi laser\nSinar laser dapat digunakan untuk membakar benjolan, mensterilkan luka, dan menutup jaringan.\n3. Electrocautery\nElectrocautery bertujuan untuk menghilangkan benjolan dengan menggunakan arus listrik. Metode ini dapat diterapkan sebagai prosedur tunggal atau dikombinasikan dengan kuret. Jika dilakukan secara hati-hati, metode ini umumnya tidak meninggalkan bekas luka.\n4. Kuret (curettage)\nKuret dilakukan dengan mengerik benjolan keratosis seboroik menggunakan alat khusus. Kuret dapat dikombinasikan dengan krioterapi atau electrocautery guna mendapatkan hasil yang lebih maksimal.\n5. Bedah konvensional\nPengangkatan keratosis seboroik dengan teknik bedah konvensional dilakukan dengan bius lokal dan sayatan pisau bedah. Setelah tindakan, luka akan dijahit.Setelah operasi pengangkatan, area kulit bekas benjolan akan berwarna lebih pucat daripada kulit di sekitarnya. Perbedaan warna akan berkurang seiring berjalannya waktu.",
  },
  {
    name: "Melanoma",
    link: "https://www.halodoc.com/kesehatan/melanoma",
    step: "Pengobatan kanker kulit mirip dengan pengobatan kanker lainnya. Namun tidak seperti kebanyakan kanker di dalam tubuh, lebih mudah untuk mengakses jaringan kanker dan menghilangkannya sepenuhnya. Untuk alasan ini, operasi adalah pilihan pengobatan standar untuk melanoma.\nJika penyakit ini dapat bermetastasis atau menyebar ke organ lain, dokter akan merekomendasikan perawatan tergantung di mana melanoma telah menyebar. Hal ini termasuk:\n1. Kemoterapi, dengan menggunakan obat yang menargetkan sel kanker.\n2. Imunoterapi, dengan menggunakan obat yang bekerja dengan sistem kekebalan untuk membantu melawan kanker.\n3. Terapi bertarget, menggunakan obat-obatan yang mengidentifikasi dan menargetkan gen atau protein tertentu yang spesifik untuk kondisi ini.\n",
  },
  {
    name: "Actinic keratosis",
    link: "https://www.halodoc.com/kesehatan/actinic-keratosis",
    step: "Pemberian obat-obatan dan terapi intervensi merupakan metode yang dilakukan oleh dokter untuk mengobati actinic keratosis. Dokter akan memilih rekomendasi terapi berdasarkan keluhan dan kondisi kulit pengidap. Pengobatan dengan obat-obatan umumnya dengan menggunakan salep untuk mengurangi gejala.\nSementara terapi intervensi yang dapat dilakukan, antara lain:\n1. Cryosurgery. Terapi ini disebut juga dengan krioterapi yang dilakukan dengan cara menggunakan nitrogen cair untuk membekukan pertumbuhan kulit. Biasanya, terapi ini membutuhkan waktu penyembuhan selama 7-14 hari.\n2. Kuretase dan electrosurgery, yaitu dengan mengikis pertumbuhan kulit abnormal.\n3. Shave excision. Tindakan ini dilakukan untuk mengangkat pertumbuhan kulit dan dilakukan pemeriksaan untuk kemungkinan keganasan.\n4. Laser resurfacing. Dilakukan penembakan cahaya laser untuk menghancurkan lapisan kulit yang paling atas dan diharapkan akan tumbuh kembali jaringan kulit normal.\n5. Chemical Peeling. Prosedur ini melibatkan pengelupasan lapisan yang tidak diinginkan di lapisan atas kulit. Dalam beberapa hari pertama, area yang ditangani dengan chemical peeling akan terasa sakit dan merah. Saat kulit sembuh, lapisan kulit baru yang sehat akan tumbuh.\n6. Terapi fotodinamik. Jika kamu memiliki beberapa kondisi actinic keratosis, atau actinic keratosis kambuh lagi setelah perawatan, dokter mungkin merekomendasikan terapi fotodinamik. Perawatan ini menggunakan krim dan terapi cahaya khusus untuk menghancurkan sel kulit yang bermasalah. Namun setelah perawatan, kamu harus menghindari sinar matahari selama beberapa hari selama kulit yang dirawat pulih.\n",
  },
  {
    name: "Psoriasis",
    link: "https://www.alodokter.com/psoriasis/pengobatan",
    step: "Pengobatan psoriasis tergantung pada tingkat keparahan psoriasis dan efektivitas perawatan sebelumnya. Metode pengobatan yang bisa dilakukan untuk mengatasi psoriasis antara lain:\n1. Emolien\nEmolien merupakan pelembab yang dapat digunakan untuk mengobati psoriasis ringan. Manfaat emolien untuk psoriasis antara lain untuk mengurangi pengelupasan kulit dan iritasi, meredakan gatal, dan mencegah perdarahan akibat goresan pada kulit.\n2. Obat oles\nPemberian obat oles bertujuan untuk meredakan gatal dan peradangan, mengurangi gejala kulit bersisik, dan menghambat pembentukan sel kulit baru. Obat oles berupa krim atau salep yang dapat diresepkan oleh dokter untuk mengobati psoriasis yaitu calcipotriol; kortikosteroid, seperti clobetasol, betamethasone, desoximetasone, atau desonide, dithranol, fluprednidene, dan tacrolimus.\n3. Fototerapi\nFototerapi atau terapi cahaya dilakukan jika psoriasis tidak dapat ditangani dengan obat oles. Prosedur ini dilakukan oleh dokter kulit menggunakan sinar ultraviolet (UV) UVA atau UVB. Jika menggunakan UVA, terapi cahaya akan dikombinasikan dengan obat jenis psoralen. Tujuannya adalah agar kulit lebih sensitif terhadap efek sinar UV.\n4. Obat minum\nPengobatan lain untuk psoriasis yang bisa diberikan oleh dokter adalah obat minum. Beberapa jenis obat yang digunakan adalah methotrexate dan ciclosporin.\n5. Obat suntikan\nObat suntik bisa diberikan untuk menangani psoriasis parah yang tidak efektif diobati dengan metode di atas. Jenis obat suntik yang dapat diberikan untuk menangani psoriasis adalah etanercept, adalimumab, secukinumab, dan infliximab.\n",
  },
  {
    name: "Dermatofibroma",
    link: "https://www.honestdocs.id/dermatofibroma",
    step: "Biasanya, dermatofibroma bersifat kronis dan tidak dapat sembuh sendiri secara spontan. Tetapi kondisi ini tidak berbahaya, dan perawatan biasanya semata-mata hanya bertujuan untuk alasan kosmetik. Pilihan pengobatan untuk dermatofibroma meliputi:\n1. Pembekuan / cryotherapy (dengan nitrogen cair)\n2. Injeksi kortikosteroid terlokalisasi\n3. Terapi laser\n4. Skin peeler\nTerapi ini mungkin tidak dapat menghilangkan dermatofibroma sepenuhnya, karena jaringan dapat terakumulasi kembali di dalam lesi dan kembali ke ukuran sebelum dilakukan terapi.\nSebuah dermatofibroma dapat sepenuhnya dihilangkan dengan eksisi bedah, tetapi ada juga kemungkinan pembentukan jaringan parut yang mungkin dianggap lebih tidak sedap dipandang daripada dermatofibroma itu sendiri.\nJangan pernah mencoba memotong atau menghilangkan dermatofibroma sendiri di rumah. Jika Anda mencoba menghilangkannya sendiri di rumah, terutama menggunakan alat-alat yang tidak steril, maka dapat menyebabkan infeksi, jaringan parut, dan perdarahan berlebih.\n",
  },
  {
    name: "Tinea Ringworm Candidiasis",
    link: "https://www.alodokter.com/candidiasis",
    step: "Tujuan pengobatan candidiasis adalah untuk mengatasi infeksi dan mencegah terjadinya komplikasi. Saat sudah didiagnosis mengalami candidiasis, dokter akan memberikan obat antijamur, sesuai dengan lokasi dan tingkat keparahan infeksi. Dokter dapat memberikan obat antijamur dalam bentuk tablet, losion, atau krim.\nObat antijamur yang dapat digunakan antara lain:\n1. Amphotericin B\n2. Butoconazole\n3. Bifonazole\n4. Caspofungin\n5. Clotrimazole\n6. Fluconazole\n7. Miconazole\n8. Itraconazole\n9. Nystatin\n10. Tioconale\n11. Voriconazole\n12. Micafungin\n",
  },
  {
    name: "Eczema",
    link: "https://www.halodoc.com/kesehatan/eksim",
    step: "Dipercaya jika belum ada obat yang dapat mengatasi eksim. Perawatan terhadap kondisi ini bertujuan untuk menyembuhkan kulit yang terserang serta mencegah gejalanya. Pengobatan yang dapat dilakukan berdasarkan berbagai faktor. Nah, berikut beberapa cara pengobatan yang bisa dilakukan:\n1. Penggunaan antihistamin. Metode ini dapat meredakan eksim yang diinduksikan oleh alergi. Namun, perlu diperhatikan jika obat ini dapat menyebabkan kantuk jika dikonsumsi secara oral. Dokter kerap menyarankan untuk menggunakan obat secara topikal.\n2. Penggunaan kortikosteroid oles. Obat ini dapat digunakan untuk menekan peradangan akibat eksim. Namun, pengobatan seperti steroid sebaiknya hanya digunakan di daerah yang mengalami peradangan dan tidak untuk area lain, terutama area luka dan wajah.\n3. Penggunaan pelembap kulit. Pilih pelembap yang benar-benar sesuai dengan kondisi kulit. Cobalah lebih sering mengoleskannya untuk menghindari masalah kulit yang lebih meluas.\n",
  },
  {
    name: "Vascular lesion",
    link: "https://skinsight.com/skin-conditions/laser-vascular-lesion-treatment/#:~:text=Laser%20treatment%20is%20usually%20the,inserted%20into%20larger%20blood%20vessels",
    step: "1. Pengobatan menggunakan laser merupakan opsi terbaik untuk vascular lesions di area wajah.\n2. Sedangkan untuk vascular lesion di daerah kaki, lebih baik menggunakan injeksi obat.\n3. Vascular lesions yang lebih kronis, dianjurkan untuk melakukan tindakan bedah atau laser kecil.\n",
  },
  {
    name: "Warts Molluscum",
    link: "https://www.alodokter.com/molluscum-contagiosum",
    step: "Moluskum kontagiosum akan sembuh dengan sendirinya tanpa pengobatan dalam 6\u201312 bulan, terutama jika penderita memiliki sistem imun yang baik. Pada beberapa kasus, penyakit ini bisa berlangsung selama lebih dari 5 tahun. Namun, orang yang sudah pernah menderita molluscum contagiosum tidak akan tertular lagi.\nPada pasien dewasa, ada beberapa metode yang bisa dilakukan oleh dokter kulit untuk mengobati moluskum kontagiosum, antara lain:\n1. Mengolesi bintil dengan asam trikloroasetat, asam salisilat, atau tretinoin, baik dalam bentuk krim maupun salep\n2. Kuret atau scraping, yaitu mengikis bintil menggunakan alat medis khusus\n3. Terapi sinar laser, yaitu membakar bintil menggunakan sinar laser\n4. Diathermy, yakni menghancurkan bintil menggunakan energi panas, dengan terlebih dahulu diberikan bius lokal\n5. Krioterapi, yaitu membekukan bintil menggunakan nitrogen cair\n",
  },
  {
    name: "Basal cell carcinoma",
    link: "https://www.alodokter.com/karsinoma-sel-basal",
    step: "Beberapa metode yang dapat dilakukan untuk menangani karsinoma sel basal adalah:\n1. Pemotongan dengan jarum elektrik\nDokter akan mengikis sel kanker di permukaan kulit, kemudian membakar sel kanker yang tersisa dengan jarum elektrik. Prosedur ini umum dilakukan pada kanker yang berukuran kecil.\n2. Pemotongan dengan pisau bedah\nDokter akan memotong area kulit yang terkena kanker dan jaringan kulit yang sehat di sekitarnya. Setelah itu, dokter akan memeriksa kulit dengan mikroskop guna memastikan tidak ada sel kanker yang tersisa. Prosedur ini dilakukan bila ukuran kanker cukup besar.\n3. Krioterapi\nDokter akan menggunakan cairan khusus yang mengandung nitrogen untuk membekukan dan membunuh sel kanker. Krioterapi atau cryosurgery biasa digunakan untuk mengatasi kanker yang tipis dan tidak terlalu dalam ke kulit.\n4. Operasi Mohs\nDokter akan mengangkat lapisan kulit yang bermasalah sedikit demi sedikit, sambil memeriksanya di bawah mikroskop untuk memastikan tidak ada sel kanker yang tertinggal. Metode ini digunakan untuk mengatasi karsinoma sel basal yang sering kambuh, berukuran cukup besar, atau terdapat di wajah.\n5. Terapi fotodinamik\nProsedur ini dilakukan dengan mengoleskan obat ke permukaan kulit yang terkena karsinoma sel basal. Setelah itu, dokter akan menyinari bagian kulit tersebut dengan sinar khusus untuk menghancurkan sel kanker.\n6. Terapi radiasi (radioterapi)\nProsedur ini biasanya digunakan pada pasien yang tidak dapat menjalani operasi. Radioterapi juga bisa dilakukan setelah operasi untuk mencegah kekambuhan.\n7. Kemoterapi\nKemoterapi dilakukan jika kanker telah menyebar ke organ lain.\n",
  },
  {
    name: "Squamous cell carcinoma",
    link: "https://www.alodokter.com/karsinoma-sel-skuamosa",
    step: "Beberapa metode yang dapat dilakukan adalah:\n1. Electrodessiccation and curettage\nElectrodessiccation and curettage adalah prosedur pengangkatan tumor dengan cara dikuret. Setelah diangkat, lapisan bawah kanker dibakar dengan menggunakan jarum elektrik.\n2. Cryosurgery\nCryosurgery atau krioterapi adalah prosedur untuk membunuh sel kanker dengan menggunakan nitrogen cair. Metode ini juga dapat dilakukan setelah kuret.\n3. Terapi laser\nTerapi laser adalah prosedur untuk mematikan sel kanker dengan menggunakan sinar laser. Metode ini digunakan pada KSS di kulit yang tidak terlalu dalam.\n4. Terapi fotodinamik\nProsedur ini dilakukan dengan pemberian obat oles berupa aminolevulinic acid ke kulit yang terserang KSS. Kulit yang telah diolesi obat tadi kemudian disinari dengan sinar khusus untuk menghancurkan sel kanker.\n5. Eksisi sederhana\nEksisi sederhana adalah prosedur pemotongan area kulit yang terkena kanker dan jaringan kulit yang sehat di sekitarnya.\n6. Bedah Mohs\nBedah Mohs adalah prosedur pengangkatan kulit yang terkena kanker, selapis demi selapis, untuk kemudian diteliti di bawah mikroskop. Metode ini biasanya dilakukan untuk mengangkat kanker di wajah, hidung dan telinga.\n7. Kemoterapi\nKemoterapi adalah metode untuk membunuh kanker yang sudah menyebar ke organ lain dengan menggunakan obat.\n",
  },
  {
    name: "Melanocytic nevus",
    link: "https://www.klikdokter.com/penyakit/masalah-kulit/nevus",
    step: "Umumnya nevus tidak memerlukan terapi, kecuali bila pasien ingin bercak berwarna itu diangkat, atau dokter mencurigai perubahan ke arah keganasan.Terapi yang dapat dipilih pada kondisi tersebut untuk adalah eksisi sederhana nevus yang dicurigai ganas.\nEksisi adalah operasi kecil dengan melakukan anastesi setempat. Prosedur ini dapat dilakukan oleh dokter umum tanpa masuk ke kamar operasi. Tindakan ini cukup aman dengan standar operasional dan tingkat kesterilan yang baik, sehingga tidak terjadi efek samping yang mengkhawatirkan pascaoperasi.\n",
  },
];

module.exports = predictionData;
